# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Corne-ish Zen"
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v2_left,corneish_zen_v2_right"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_DISPLAY_FULL_REFRESH_PERIOD=10\nCONFIG_CUSTOM_WIDGET_LAYER_STATUS_HIDE_HEADING=y\nCONFIG_ZMK_MOUSE=y\nCONFIG_CUSTOM_WIDGET_LOGO_IMAGE_MIRYOKU=y\nCONFIG_IL0323_INVERT=y\nCONFIG_ZMK_DISPLAY_HIDE_MOMENTARY_LAYERS=y"]'
      branches: '["zmkfirmware/zmk/main caksoylar/zmk/caksoylar/zen-v1+v2 ftc/zmk/mouse-ftc"]'
